@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Doctor as doc
participant " <<Container(C4)>>\n FrontEnd" as sys
participant "<<Container(C4)>>\nBackEnd" as backEnd
participant "Planning Module" as planning
participant "Database" as DB

title Process View - Level 2


activate doc

doc -> sys: request to update an existing operation

activate sys


sys -> backEnd : GET /operations (fetch operations by doctor)

activate backEnd


backEnd -> DB : Fetch all operations by doctor
activate DB

DB --> backEnd : Return all operations by doctor
deactivate DB


backEnd --> sys : returns list of operations created by doctor

deactivate backEnd

sys --> doc: shows list of operations and asks to select one


doc -> sys: selects an operation to update


sys -> backEnd : GET /operationDetails (for selected operation)
activate backEnd
backEnd -> DB : Fetch all operations by doctor
activate DB

DB --> backEnd : Return all operations by doctor

deactivate DB




backEnd --> sys : returns current operation details

deactivate backEnd

sys --> doc: shows current operation details (deadline, priority) and asks for update


doc -> sys: updates priority or deadline


sys -> backEnd : PUT /updateOperation (with updated details)

activate backEnd

alt verification process is successful

    backEnd -> backEnd : check if doctor can update the operation

    backEnd --> sys: returns success message (operation updated)

    sys --> doc: shows success message with updated operation data (priority, deadline)

    sys -> planning : notify changes to Planning Module

    activate planning

    planning --> sys : confirmation of update received

    deactivate planning


else error in the verification process

    backEnd --> sys: returns error message (operation update failed)

    deactivate backEnd

    sys --> doc: shows message of failure of the update

end

deactivate sys
deactivate planning
deactivate doc

@enduml
