@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Admin as doc
participant "<<System(C4)>>\nSystem" as sys
title Process View - Level 1



activate doc

doc -> sys: request to update an exiting operation type

activate sys

sys --> doc: shows list of operation types and asks to select one
doc -> sys: selects an operation type to edit

sys --> doc: shows current operation type details (operation name,\n required staff by specialization, and estimated duration)
doc -> sys: edits the operation type details

alt verification process is successful
    sys --> doc: operation updated successfully
else error in the verification process
    sys --> doc: error message (update failed)
end

deactivate sys
deactivate doc

@enduml
