@startuml
'autonumber
participant FrontEnd as fe
participant "PatientController" as ctrl
participant "PatientService" as serv
participant "PatientAccount" as operation
participant "DataBase" as repo <<repository>>
participant "Planning Module" as planning

participant "EmailService" as es


activate fe

fe -> ctrl: asks to delete his account
activate ctrl

ctrl -> es: send confirmation email to the patient before\n proceeding with account deletion
activate es

es --> fe: sends a confirmation email
deactivate es

deactivate ctrl

fe -> ctrl: confirmation of deletion
activate ctrl



alt deletion is successful

fe -> ctrl : DELETE /patient (request to delete operation)

    ctrl -> serv: deletePatient(patientId)

    activate serv

    serv -> repo: removePatientById(patientId)

    activate repo

    repo --> serv: patient deleted from DB

    deactivate repo

    serv --> ctrl: deletion successful

    deactivate serv

    ctrl --> fe: returns success message (operation deleted)



else deletion cancelled

    ctrl --> fe: returns cancellation message

    deactivate ctrl

end

@enduml