@startuml
autonumber
participant "                          " as sys
participant "<<application>>\nOperationRequestController" as ctrl
participant "<<service>>\nOperationRequestService" as serv
participant "OperationRequestDTO" as dto
participant "OperationRequestMapper" as map
participant "<<domain>>\nOperationRequest" as operation
participant "OperationRequestRepository" as repo <<repository>>

title Process View Backend Container - Level 3


activate sys

sys -> ctrl : GET /patients
note right of ctrl
  The requested actions ( GET ) are already documented in global documentation
end note

activate ctrl
ctrl --> sys : returns list of patients
deactivate ctrl


sys -> ctrl : GET /operationTypes

activate ctrl

ctrl --> sys : returns list of operation types
deactivate ctrl

sys -> ctrl : find priority options
activate ctrl
ctrl --> sys : returns list of priorities
deactivate ctrl




sys -> ctrl : POST /operations (with given data)



activate ctrl

note right of ctrl
  The requested actions ( POST ) are already documented in global documentation

end note


ctrl --> sys : returns success message




deactivate ctrl
deactivate sys

@enduml
