@startuml
autonumber
participant "                          " as sys
participant "OperationController" as ctrl
participant "OperationService" as serv
participant "OperationDTO" as dto
participant "OperationMapper" as map
participant "Operation" as operation
participant "Repository" as repo <<repository>>

title Process View Backend Container - Level 3


activate sys

sys -> ctrl : GET /patients
note right of ctrl
  The requested actions ( GET ) are already documented in other user story


end note

activate ctrl
ctrl --> sys : returns list of patients
deactivate ctrl


sys -> ctrl : GET /operationTypes








activate ctrl


ctrl --> sys : returns list of operation types
deactivate ctrl

sys -> ctrl : find priority options
activate ctrl
ctrl --> sys : returns list of priorities
deactivate ctrl

sys -> ctrl : POST /operations (with given data)
activate ctrl

alt verification process is successful
  ctrl -> serv : verify and create operation
  activate serv

  serv -> dto : create OperationDTO from request data
  activate dto
  dto --> serv : OperationDTO created
  deactivate dto

  serv -> map : map DTO to domain
  activate map
  map -> operation : create Operation entity from DTO
  activate operation
  operation --> map : Operation entity created
  deactivate operation
  map --> serv : mapped to Operation entity
  deactivate map

  serv -> repo : save operation in database
  activate repo
  repo --> serv : operation saved successfully
  deactivate repo

  serv --> ctrl : operation saved, success response
  deactivate serv

  ctrl --> sys : returns success message
else error in the verification process
  ctrl --> sys : shows message of failure of the verification process
end

deactivate ctrl
deactivate sys

@enduml
