@startuml
autonumber
participant "                          " as sys
participant "<<application>>\nOperationRequestController" as ctrl
participant "<<service>>\nOperationRequestService" as serv
participant "OperationRequestDTO" as dto
participant "OperationRequestMapper" as map
participant "<<domain>>\nOperationRequest" as operation
participant "OperationRequestRepository" as repo <<repository>>

title Process View Backend Container - Level 3


activate sys

sys -> ctrl : GET /patients

note right of ctrl
  The requested actions ( GET ) are already documented in global documentation
end note

activate ctrl
ctrl --> sys : returns list of patients
deactivate ctrl

sys -> ctrl : GET /operationTypes

activate ctrl


ctrl --> sys : returns list of operation types
deactivate ctrl

sys -> ctrl : find priority options
activate ctrl
ctrl --> sys : returns list of priorities
deactivate ctrl

sys -> ctrl : POST /operationRequest (with given data)
activate ctrl

alt verification process is successful
  ctrl -> serv : verify and create operation
  activate serv

  serv -> dto : create OperationRequestDTO from request data
  activate dto
  dto --> serv : OperationRequestDTO created
  deactivate dto

  serv -> map : map DTO to domain
  activate map
  map -> operation : create Operation request entity from DTO
  activate operation
  operation --> map : Operation request entity created
  deactivate operation
  map --> serv : mapped to Operation request entity
  deactivate map

  serv -> repo : save operation request in database
  activate repo
  repo --> serv : operation request saved successfully
  deactivate repo

  serv --> ctrl : operation request saved, success response
  deactivate serv

  ctrl --> sys : returns success message
else error in the verification process
  ctrl --> sys : shows message of failure of the verification process
end

deactivate ctrl
deactivate sys

@enduml
