@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Patient as patient
participant "<<System(C4)>>\nHealthcare System" as sys
participant "External IAM System" as iam
participant "Email Service" as email

activate patient
patient -> sys: Register for healthcare application

activate sys
sys -> iam: Forward registration details

activate iam
iam --> sys: Registration successful
deactivate iam

sys -> email: Send verification email
activate email
email --> patient: Verification email sent
deactivate email

sys --> patient: Registration successful, verify email to complete

deactivate sys
deactivate patient

@enduml