@startuml Process View - Level 1

autonumber
skinparam packageStyle rect

title Create Resource

participant "System" as RDG <<system (C4)>>

-> RDG: User fills out form with resource details

activate RDG

alt resource Created

  <-- RDG: sends message of resource created successfully

else invalid input

  <-- RDG: sends message of invalid input

else unauthorized

  <-- RDG: sends message of unauthorized

else necessary resource not found

  <-- RDG: sends message of necessary resource not found

else resource already exists

  <-- RDG: sends message of resource already exists

else database unavailable

  <-- RDG: sends message of database unavailable

end

@enduml