@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Doctor as doc
participant "FrontEnd" as sys
participant "Backend"
activate doc

doc -> sys: request to create a new operation

activate sys


sys -> "Backend" : GET /patients

activate "Backend"

"Backend" --> sys : returns list of patients

deactivate "Backend"


sys --> doc: shows list of patients and asks to select one


doc -> sys: selects a patient


sys -> "Backend" : GET /operationTypes

activate "Backend"

"Backend" --> sys : returns list of operation types

deactivate "Backend"

sys --> doc: shows list of operation types and asks to select one




deactivate "Backend"

doc -> sys: selects an operation type



sys -> "Backend" : find priority options

activate "Backend"

"Backend" --> sys : returns list of priority options

deactivate "Backend"

sys --> doc : shows list of priority options and asks to select one





doc -> sys: selects a priority option



sys --> doc: requests suggested deadline for the operation



doc -> sys: defines a suggested deadline







sys -> "Backend" : POST /operations ( with given data )

activate "Backend"

alt verification process is successful


"Backend" --> sys : returns success message


  sys --> doc: shows data of the operation request \n(patient ID, doctor ID, type, deadline, priority)


else error in the verification process

"Backend" --> sys : returns success message

deactivate "Backend"

  sys --> doc: shows message of failure of the verification process

  deactivate sys

end

@enduml