@startuml
autonumber
skinparam packageStyle rect

title Back-End get resources - Logical View LV3

participant AspnetRouter as router
participant ResourceController as ctrl
participant ResourceService as service
participant ResourceDTO as dto
participant ResourceMapper as mapper
participant ResourceRepository as repo
participant Resource as domain

-> router: GET /resource
activate router
router -> ctrl: getAllResources()
activate ctrl
ctrl -> service: getAllResources()
activate service
service -> repo: fetchAll()
activate repo
repo --> service: returns all resource entities
deactivate repo

service -> mapper: mapEntitiesToDTOs()
activate mapper
mapper --> service: returns mapped resource DTOs
deactivate mapper

service --> ctrl: returns resource DTOs
deactivate service

ctrl --> router: returns resource DTOs
deactivate ctrl
deactivate router

@enduml
