@startuml
autonumber
skinparam packageStyle rect

title Back-End GET resources - Logical View LV3

participant AspnetRouter as router
participant ResourceController as ctrl
participant ResourceService as service
participant ResourceDTO as dto
participant ResourceMapper as mapper
participant ResourceRepository as repo


note over router
This diagram is a generic representation of any database asset
end note


-> router: GET /resource
activate router

router -> ctrl: getAllResources()
activate ctrl

ctrl -> service: getAllResources()
activate service

service -> repo: fetchAllResources()

activate repo


repo -> : Fetch all resources

repo <-- : returns resource entities


repo --> service: returns resource entities
deactivate repo

service -> mapper: mapResourcesToDTOs(resource entities)
activate mapper

mapper --> service: returns mapped resource DTOs
deactivate mapper

service --> ctrl: returns resource DTOs
deactivate service

ctrl --> router: returns resource DTOs
deactivate ctrl

 <-- router : returns resource DTOs
deactivate router

@enduml
