@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Doctor as doc
participant "<<System(C4)>>\nVisualização" as sys

activate doc

doc -> sys: request to create a new operation

activate sys

sys --> doc: shows list of patients and asks selection of one
doc -> sys: selects a patient

deactivate sys

sys --> doc: shows operation types and asks selection of one

activate sys


doc -> sys: selects an operation type
deactivate sys


sys --> doc: shows priority options and asks selection of one
activate sys

doc -> sys: selects a priority option

deactivate sys


sys --> doc: requests suggested deadline for the operation
activate sys

doc -> sys: defines a suggested deadline







alt verification process is successful

  sys --> doc: shows data of the operation request \n(patient ID, doctor ID, type, deadline, priority)


else error in the verification process

  sys --> doc: shows message of failure of the verification process

  deactivate sys

end

@enduml