@startuml
autonumber
skinparam packageStyle rect

title Back-End post resources - Logical View LV3

participant AspnetRouter as router
participant ResourceController as ctrl
participant ResourceService as service
participant ResourceDTO as dto
participant ResourceMapper as mapper
participant ResourceRepository as repo
participant Resource as domain

-> router: PUT /resource
activate router
router -> ctrl: createResource(resourceDTO)
activate ctrl
ctrl -> service: create(resourceDTO)
activate service
service -> mapper: mapToDomain(resourceDTO)
activate mapper
mapper --> domain** : <<create>>
mapper --> service : returns domain
deactivate mapper
service -> service: validate(domain)
service -> repo: save(domain)
activate repo
repo --> service : returns domain
deactivate repo
service -> mapper: mapToDTO(domain)
activate mapper
mapper --> service : returns resourceDTO
deactivate mapper
service --> ctrl : returns resourceDTO
deactivate service
ctrl --> router : returns resourceDTO




@enduml
