@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Doctor as doc
participant "<<Container(C4)>>\nFrontEnd" as sys
participant "<<Container(C4)>>\nBackend" as BE
participant "DataBase" as DB <<C4 Container>>
activate doc

title Process View - Level 2

note right of doc
  The requested actions ( GET ) and ( POST ) are already documented in global documentation
end note


doc -> sys: request to create a new operation request

activate sys


sys -> BE : GET /patients

activate BE

BE -> DB: Fetch all patients
activate DB
DB --> BE: Returns all patients
deactivate DB



BE --> sys : returns list of patients

deactivate BE




sys --> doc: shows list of patients and asks to select one


doc -> sys: selects a patient


sys -> BE : GET /operationTypes

activate BE

BE -> DB: Fetch all operationTypes
activate DB
DB --> BE: Returns all operationTypes
deactivate DB


BE--> sys : returns list of operation types

deactivate BE

sys --> doc: shows list of operation types and asks to select one




deactivate BE

doc -> sys: selects an operation type



sys -> BE: find priority options

activate BE

BE --> sys : returns list of priority options

deactivate BE

sys --> doc : shows list of priority options and asks to select one





doc -> sys: selects a priority option



sys --> doc: requests suggested deadline for the operation



doc -> sys: defines a suggested deadline







sys -> BE: POST /operations ( with given data )

activate BE


BE -> DB : insert new resource into database
activate DB
DB --> BE: Returns success response

deactivate DB


alt verification process is successful


BE --> sys : returns success message


  sys --> doc: shows data of the operation request \n(patient ID, doctor ID, type, deadline, priority)


else error in the verification process

BE --> sys : returns success message

deactivate BE

  sys --> doc: shows message of failure of the verification process

  deactivate sys

end

@enduml