@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "                          " as sys
participant "<<application>>\nRegisterPatientController" as ctrl
participant "<<service>>\nRegisterPatientService" as svc
participant "RegisterPatientMapper" as mapper
participant "RegisterPatientDTO" as dto
participant "<<domain>>\nPatient" as app
participant "PatientRepository" as repo <<repository>>
participant "EmailService" as email

activate sys

sys -> ctrl: Register for healthcare application

activate ctrl

ctrl -> svc: Forward registration details

activate svc



svc -> mapper: Map DTO to domain
activate mapper

mapper -> app : create Application entity from DTO
activate app

app --> mapper : Application entity created

deactivate app

mapper --> svc: Application entity mapped
deactivate mapper

svc -> repo: Store patient data
activate repo

repo --> svc: Data stored
deactivate repo

svc -> mapper: Create RegisterHealthcareDTO from registration details
deactivate repo

activate mapper

mapper --> dto: RegisterHealthcareDTO created
activate dto

dto --> mapper: dto created
deactivate dto

mapper --> svc: RegisterHealthcareDTO created
deactivate mapper


alt Email sent successfully
    svc -> email: Send verification email
    activate email
    email --> svc: Verification email sent
    deactivate email
    svc --> ctrl: Registration successful
    
    ctrl --> sys: Registration successful
    
else Email sending failed
    svc -> email: Send verification email
    activate email
    
    email --> svc: Email sending failed
    deactivate email
    svc --> ctrl: Registration unsuccessful, email sending failed
    
    ctrl --> sys: Registration unsuccessful, email sending failed
end
deactivate svc

deactivate ctrl

deactivate sys

@enduml