@startuml
'https://plantuml.com/component-diagram

title "Logical View (Level 2) of SARM"

component "IAM_API" as IAM_API
component "WebUI" as WebUI 

component SARM<<System>> as SARM{
    component "Web Application" <<BackOffice>> as BO
    component "Planning/Optimization" <<Planning>> as PO
 
 WebUI -down-0 BO 
 BO -right-(0 PO
 BO -down-( IAM_API
 
 
 }





@enduml